import Head from "next/head";
import { Button } from "@/components/Button/Button";
import router from "next/router";
import { useShopContext } from "@/hooks/useShop";
import { useUtilityContext } from "@/hooks/useUtility";
import { Loading } from "@/components/Loading/Loading";

export const Index = () => {
  const { setCurrentShop } = useShopContext();
  const { isLoadingShow, lodingShow, lodingHide } = useUtilityContext();
  const hundleClick = async (genre: string) => {
    try {
      lodingShow();
      await setCurrentShop(genre);
      router.push("/list");
      lodingHide();
    } catch (error) {
      console.log("失敗");
      console.log(error);
      lodingHide();
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-screen w-screen flex justify-center items-center">
          {isLoadingShow ? (
            <Loading />
          ) : (
            <div className="flex justify-between w-10/12">
              <Button onClick={() => hundleClick("G001")}>居酒屋</Button>
              <Button onClick={() => hundleClick("G012")}>バー</Button>
            </div>
          )}
        </div>
      </main>
    </>
  );
};
